// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { GetByIdData, GetByIdError, GetByIdResponse, SaveUserData, SaveUserError, SaveUserResponse, GetAllUsersData, GetAllUsersError, GetAllUsersResponse, AddUserData, AddUserError, AddUserResponse } from './types.gen';

export const client = createClient(createConfig());

export const getById = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetByIdResponse, GetByIdError, ThrowOnError>({
        ...options,
        url: '/api/users/{id}'
    });
};

export const saveUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SaveUserData, ThrowOnError>) => {
    return (options?.client ?? client).put<SaveUserResponse, SaveUserError, ThrowOnError>({
        ...options,
        url: '/api/users/{id}'
    });
};

export const getAllUsers = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<GetAllUsersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllUsersResponse, GetAllUsersError, ThrowOnError>({
        ...options,
        url: '/api/users'
    });
};

export const addUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<AddUserData, ThrowOnError>) => {
    return (options?.client ?? client).post<AddUserResponse, AddUserError, ThrowOnError>({
        ...options,
        url: '/api/users'
    });
};