// This file is auto-generated by @hey-api/openapi-ts

export type PaginationUserList = {
    items: Array<UserList>;
    currentPage: number;
    totalItems: number;
    pageSize: number;
    lastPage?: boolean;
};

export type User = {
    id?: string;
    username: string;
    password: string;
    email: string;
    avatar?: string;
};

export type UserList = {
    id?: string;
    username?: string;
};

export type GetByIdData = {
    path: {
        id: string;
    };
};

export type GetByIdResponse = (User);

export type GetByIdError = unknown;

export type SaveUserData = {
    body: User;
    path: {
        id: string;
    };
};

export type SaveUserResponse = (User);

export type SaveUserError = unknown;

export type GetAllUsersData = {
    query?: {
        page?: number;
        size?: number;
    };
};

export type GetAllUsersResponse = (PaginationUserList);

export type GetAllUsersError = unknown;

export type AddUserData = {
    body: User;
};

export type AddUserResponse = (User);

export type AddUserError = unknown;